"""added phone number

Revision ID: 416db5704af2
Revises: 269f746f80b0
Create Date: 2022-11-09 16:56:29.138692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416db5704af2'
down_revision = '269f746f80b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
